
package jdo.spc.bsm;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-05-21T08:54:31.437+08:00
 * Generated source version: 2.5.2
 * 
 */
public final class ConsisServiceSoap_ConsisServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.willach.com/", "ConsisService");

    public ConsisServiceSoap_ConsisServiceSoap_Client() {
    }
    /**
     * 
     * @param _transConsisData_opstr
     * @return
     */
    public static String onTransConsisData(String  _transConsisData_opstr){
    	String _transConsisData__return = "" ;
    	try {
    		 URL wsdlURL = ConsisService.WSDL_LOCATION;
        	 ConsisService ss = new ConsisService(wsdlURL, SERVICE_NAME);
             ConsisServiceSoap port = ss.getConsisServiceSoap();  
        	 _transConsisData__return =port.transConsisData(_transConsisData_opstr) ;
        	return _transConsisData__return ;
		} catch (Exception e) {
			System.out.println("======"+e.toString());  
			_transConsisData__return = "err"  ;
		}
    	return _transConsisData__return ;
    }
}
