  #
   # Title:盘点管理工具
   #
   # Description:盘点管理工具
   #
   # Copyright: JavaHis (c) 2011
   #
   # @author shibl 2011/06/10
Module.item=queryM;queryD;updateM;insertD;deleteD

//根据条件查询主表记录
queryM.Type=TSQL
queryM.SQL=SELECT HOSP_AREA, DEPT_CODE, DEV_CODE, BATCH_SEQ, QTY, UNIT_PRICE, &
       		 MAN_DATE, SCRAP_VALUE, GUAREP_DATE, DEP_DATE, FILES_WAY, &
       		   CARE_USER, USE_USER, LOC_CODE, INWAREHOUSE_DATE, STOCK_FLG, &
       		 BATCH_CODE, SUP_CODE, &
       		 OPT_USER, OPT_DATE, OPT_TERM &
       	    FROM DEV_STOCKM &
       	    ORDER BY DEV_CODE
queryM.ITEM=DEPT_CODE;HOSP_AREA;DEV_CODE;BATCH_SEQ
queryM.DEPT_CODE=DEPT_CODE=<DEPT_CODE>
queryM.HOSP_AREA=HOSP_AREA=<HOSP_AREA>
queryM.BATCH_SEQ=BATCH_SEQ=<BATCH_SEQ>
queryM.DEV_CODE=DEV_CODE=<DEV_CODE>
queryM.Debug=N

//根据条件查询细表记录
queryD.Type=TSQL
queryD.SQL=SELECT HOSP_AREA,DEV_CODE,BATCH_SEQ,DEVSEQ_NO,DEPT_CODE, SETDEV_CODE, UNIT_PRICE, QTY,&
       		   MAN_DATE, SCRAP_VALUE, GUAREP_DATE, DEP_DATE,MANSEQ_NO, &
       		   CARE_USER, USE_USER, LOC_CODE, INWAREHOUSE_DATE, &
       		   BATCH_CODE, SUP_CODE, &
       		 OPT_USER, OPT_DATE, OPT_TERM &
       	    FROM DEV_STOCKD &
       	    ORDER BY DEV_CODE
queryD.ITEM=DEVSEQ_NO;HOSP_AREA;DEV_CODE;BATCH_SEQ
queryD.DEVSEQ_NO=DEVSEQ_NO=<DEVSEQ_NO>
queryD.HOSP_AREA=HOSP_AREA=<HOSP_AREA>
queryD.BATCH_SEQ=BATCH_SEQ=<BATCH_SEQ>
queryD.DEV_CODE=DEV_CODE=<DEV_CODE>

queryD.Debug=N

//保存盘点数据
updateM.Type=TSQL
updateM.SQL=UPDATE DEV_STOCKM SET &
				   QTY=<QTY> , &
				   OPT_USER=<OPT_USER> , &
				   OPT_DATE=TO_DATE(<OPT_DATE>,'YYYYMMDDHH24MISS') , &
				   OPT_TERM=<OPT_TERM> &
			     WHERE DEPT_CODE=<DEPT_CODE> & 
			       AND DEV_CODE=<DEV_CODE> &
			       AND HOSP_AREA=<HOSP_AREA> &
			       AND BATCH_SEQ=<BATCH_SEQ> 
updateM.Debug=N
//新增细表数据
insertD.Type=TSQL
insertD.SQL=INSERT INTO DEV_STOCKD( &
		 HOSP_AREA,DEV_CODE,BATCH_SEQ,DEVSEQ_NO,DEPT_CODE, SETDEV_CODE, UNIT_PRICE, QTY,&
       		   MAN_DATE, SCRAP_VALUE, GUAREP_DATE, DEP_DATE,MANSEQ_NO, &
       		   CARE_USER, USE_USER, LOC_CODE, INWAREHOUSE_DATE, &
       		   BATCH_CODE, SUP_CODE, &
       		 OPT_USER, OPT_DATE, OPT_TERM) &
	   VALUES( &
	        <HOSP_AREA>, <DEV_CODE>, <BATCH_SEQ>, <DEVSEQ_NO>, <DEPT_CODE>, &
		<SETDEV_CODE>, <UNIT_PRICE>, <QTY>, TO_DATE(<MAN_DATE>,'YYYYMMDD'), <SCRAP_VALUE>, &
		TO_DATE(<GUAREP_DATE>,'YYYYMMDD'), TO_DATE(<DEP_DATE>,'YYYYMMDD'), <MANSEQ_NO>, <CARE_USER>, <USE_USER>,<LOC_CODE>,TO_DATE(<INWAREHOUSE_DATE>,'YYYYMMDD') ,&
		<BATCH_CODE>,<SUP_CODE>, <OPT_USER>,TO_DATE(<OPT_DATE>,'YYYYMMDDHH24MISS') , <OPT_TERM>)
insertD.Debug=N
//删除细表
deleteD.Type=TSQL
deleteD.SQL=DELETE FROM DEV_STOCKD WHERE HOSP_AREA=<HOSP_AREA> AND DEV_CODE=<DEV_CODE> AND BATCH_SEQ=<BATCH_SEQ> AND DEVSEQ_NO=<DEVSEQ_NO>
deleteD.ITEM=DEVSEQ_NO;HOSP_AREA;DEV_CODE;BATCH_SEQ
deleteD.DEVSEQ_NO=DEVSEQ_NO=<DEVSEQ_NO>
deleteD.HOSP_AREA=HOSP_AREA=<HOSP_AREA>
deleteD.BATCH_SEQ=BATCH_SEQ=<BATCH_SEQ>
deleteD.DEV_CODE=DEV_CODE=<DEV_CODE>
deleteD.Debug=N






