# 
#  Title:设备追踪操作module
# 
#  Description:设备追踪操作module
# 
#  Copyright: Copyright (c) Javahis 2008
# 
#  author sundx 2012.11.21
#  version 1.0
#
Module.item=selectDevTrackInfM;selectDevTrackInfD;updateDevRFIDBaseNormal;selectRFIDDevice;updateDevRFIDBaseOnpass;selectDevCodeByRFID;insertDevTrackInf;selectRFIDRealtime

//检索设备追踪主表信息 DEV_RFIDBASE
selectDevTrackInfM.Type=TSQL
selectDevTrackInfM.SQL=SELECT B.RFID,A.DEV_CHN_DESC,A.SPECIFICATION,C.CHN_DESC AS DEVKIND_NAME,C2.CHN_DESC AS DEVPRO_NAME, &
			D.DEPT_CHN_DESC AS DEVKEEP_NAME,D2.DEPT_CHN_DESC AS DEVLOCATION_NAME,B.DEV_STATUS AS STATUS, &
			E.MAN_CHN_DESC &
			FROM DEV_BASE A,DEV_RFIDBASE B, SYS_DICTIONARY C, SYS_DICTIONARY C2, &
			SYS_DEPT D,SYS_DEPT D2,SYS_MANUFACTURER E &
			WHERE B.DEV_CODE=A.DEV_CODE AND A.DEVKIND_CODE=C.ID AND C.GROUP_ID='DEVKIND_CODE' &
			AND A.DEVPRO_CODE=C2.ID AND C2.GROUP_ID='DEVPRO_CODE' &
			AND B.DEV_KEEPDEPT=D.DEPT_CODE AND B.DEV_LOCATIONDEPT=D2.DEPT_CODE &
			AND A.MAN_CODE=E.MAN_CODE 
selectDevTrackInfM.item=DEV_KEEPDEPT;DEV_LOCATIONDEPT;RFID;DEVKIND_CODE;DEVPRO_CODE;DEV_CHN_DESC;MAN_CODE
//保管部门
selectDevTrackInfM.DEV_KEEPDEPT=B.DEV_KEEPDEPT = <DEV_KEEPDEPT>
// 当前位置
selectDevTrackInfM.DEV_LOCATIONDEPT=B.DEV_LOCATIONDEPT = <DEV_LOCATIONDEPT>
// 设备代码
selectDevTrackInfM.RFID=B.RFID = <RFID>
// 设备类别
selectDevTrackInfM.DEVKIND_CODE=A.DEVKIND_CODE = <DEVKIND_CODE>
// 设备属性
selectDevTrackInfM.DEVPRO_CODE=A.DEVPRO_CODE = <DEVPRO_CODE>
// 设备名称
selectDevTrackInfM.DEV_CHN_DESC=A.DEV_CHN_DESC LIKE <DEV_CHN_DESC>||'%'
// 生产厂商
selectDevTrackInfM.MAN_CODE=A.MAN_CODE = <MAN_CODE>
selectDevTrackInfM.Debug=N


//检索设备追踪详细表信息 DEV_TRACK
selectDevTrackInfD.Type=TSQL
selectDevTrackInfD.SQL=SELECT B.RFID,A.DEV_CHN_DESC,A.SPECIFICATION,B.INOUT_TIME,B.INOUT_STATUS,C.DEPT_CHN_DESC &
			FROM DEV_BASE A,DEV_TRACK B,SYS_DEPT C &
			WHERE B.DEV_CODE=A.DEV_CODE AND B.INOUT_DEPT=C.DEPT_CODE &
			AND RFID=<RFID> &
			ORDER BY B.INOUT_TIME DESC
selectDevTrackInfD.Debug=N


// 插入设备追踪记录
insertDevTrackInf.Type=TSQL
insertDevTrackInf.SQL=INSERT INTO DEV_TRACK (RFID,INOUT_TIME,INOUT_STATUS,INOUT_DEPT,INOUT_CHN_DEPT,DEV_CODE,STATION_CODE,STATION_DESC) VALUES &
			(<RFID>,<INOUT_TIME>,<INOUT_STATUS>,<INOUT_DEPT>,<INOUT_CHN_DEPT>,<DEV_CODE>,<STATION_CODE>,<STATION_DESC>)
insertDevTrackInf.Debug=N

// 更新设备RFID状态-正常
updateDevRFIDBaseNormal.Type=TSQL
updateDevRFIDBaseNormal.SQL=UPDATE DEV_RFIDBASE SET DEV_LOCATIONDEPT=<INOUT_DEPT>, DEV_STATUS=1 &
			WHERE RFID=<RFID>
updateDevRFIDBaseNormal.Debug=N

// 更新设备RFID状态-在途
updateDevRFIDBaseOnpass.Type=TSQL
updateDevRFIDBaseOnpass.SQL=UPDATE DEV_RFIDBASE SET DEV_LOCATIONDEPT='', DEV_STATUS=0 &
			WHERE RFID=<RFID>
updateDevRFIDBaseOnpass.Debug=N


// 根据rfid查询dev_code
selectDevCodeByRFID.Type=TSQL
selectDevCodeByRFID.SQL=SELECT DEV_CODE FROM DEV_RFIDBASE WHERE RFID=<RFID>
selectDevCodeByRFID.Debug=N


// 实时查询设备追踪数据
selectRFIDRealtime.Type=TSQL
selectRFIDRealtime.SQL=SELECT B.RFID,A.DEV_CHN_DESC,A.SPECIFICATION,C.CHN_DESC AS DEVKIND_NAME,C2.CHN_DESC AS DEVPRO_NAME,  &
			D.DEPT_CHN_DESC AS DEVKEEP_NAME,D2.DEPT_CHN_DESC AS DEVLOCATION_NAME,B.DEV_STATUS AS STATUS,  &
			E.MAN_CHN_DESC,F.INOUT_TIME,F.INOUT_STATUS,F.INOUT_CHN_DEPT,F.STATION_DESC &
			FROM DEV_BASE A,DEV_RFIDBASE B, SYS_DICTIONARY C, SYS_DICTIONARY C2,  &
			SYS_DEPT D,SYS_DEPT D2,SYS_MANUFACTURER E, DEV_TRACK F  &
			WHERE B.DEV_CODE=A.DEV_CODE AND A.DEVKIND_CODE=C.ID AND C.GROUP_ID='DEVKIND_CODE'  &
			AND A.DEVPRO_CODE=C2.ID AND C2.GROUP_ID='DEVPRO_CODE'  &
			AND B.DEV_KEEPDEPT=D.DEPT_CODE AND B.DEV_LOCATIONDEPT=D2.DEPT_CODE(+)  &
			AND A.MAN_CODE=E.MAN_CODE AND B.RFID=F.RFID &
			ORDER BY F.INOUT_TIME DESC
selectRFIDRealtime.Debug=N