
package jdo.spc.bsm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "jdo.spc.bsm.client.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "jdo.spc.bsm.client.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdPhaBaseWs", action = "http://tempuri.org/UpdPhaBaseWs")
    @WebResult(name = "UpdPhaBaseWsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdPhaBaseWs", targetNamespace = "http://tempuri.org/", className = "jdo.spc.bsm.client.UpdPhaBaseWs")
    @ResponseWrapper(localName = "UpdPhaBaseWsResponse", targetNamespace = "http://tempuri.org/", className = "jdo.spc.bsm.client.UpdPhaBaseWsResponse")
    public String updPhaBaseWs();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdSysDeptWs", action = "http://tempuri.org/UpdSysDeptWs")
    @WebResult(name = "UpdSysDeptWsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdSysDeptWs", targetNamespace = "http://tempuri.org/", className = "jdo.spc.bsm.client.UpdSysDeptWs")
    @ResponseWrapper(localName = "UpdSysDeptWsResponse", targetNamespace = "http://tempuri.org/", className = "jdo.spc.bsm.client.UpdSysDeptWsResponse")
    public String updSysDeptWs();

    /**
     * 
     * @param strXmlInfo    
     * @return
     *     returns java.lang.String
     */
//    @WebMethod(operationName = "drugToHisAccount",action = "http://tempuri.org/drugToHisAccount")
//    @WebResult(name = "drugToHisAccountResult")
//    @RequestWrapper(localName = "drugToHisAccount", targetNamespace = "http://tempuri.org/", className = "jdo.spc.bsm.client.DrugToHisAccount")
//    @ResponseWrapper(localName = "drugToHisAccountResponse", targetNamespace = "http://tempuri.org/", className = "jdo.spc.bsm.client.DrugToHisAccountResponse")
    public String drugToHisAccount(
        @WebParam(name = "strXmlInfo", targetNamespace = "http://tempuri.org/")
        String strXmlInfo);

}
