
package jdo.spc.bsm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.dongyang.config.TConfig;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SPCHisService", targetNamespace = "http://ws.sys.jdo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SPCHisService {
	  /**
     * 
     * @param strXmlInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://ws.sys.jdo/drugToHisAccount")
    @WebResult(name = "drugToHisAccountResult", targetNamespace = "http://ws.sys.jdo/")
    @RequestWrapper(localName = "DrugToHisAccount", targetNamespace = "http://tempuri.org/", className = "jdo.spc.bsm.client.DrugToHisAccount")
    @ResponseWrapper(localName = "DrugToHisAccountResponse", targetNamespace = "http://tempuri.org/", className = "jdo.spc.bsm.client.DrugToHisAccountResponse")
    public String drugToHisAccount(
        @WebParam(name = "strXmlInfo", targetNamespace = "http://ws.sys.jdo/")
        String strXmlInfo);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdSysDeptWs")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UpdSysDeptWs", targetNamespace = "http://ws.bsm.spc.jdo/", className = "jdo.spc.bsm.his.UpdSysDeptWs")
    @ResponseWrapper(localName = "UpdSysDeptWsResponse", targetNamespace = "http://ws.bsm.spc.jdo/", className = "jdo.spc.bsm.his.UpdSysDeptWsResponse")
    public String updSysDeptWs();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdPhaBaseWs")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UpdPhaBaseWs", targetNamespace = "http://ws.bsm.spc.jdo/", className = "jdo.spc.bsm.his.UpdPhaBaseWs")
    @ResponseWrapper(localName = "UpdPhaBaseWsResponse", targetNamespace = "http://ws.bsm.spc.jdo/", className = "jdo.spc.bsm.his.UpdPhaBaseWsResponse")
    public String updPhaBaseWs();
    
}
