package jdo.bil.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-05-05T10:29:57.361+08:00
 * Generated source version: 2.5.2
 *    
 */
@WebService(targetNamespace = "http://ope.jdo/", name = "OPEPackageWsTool")
@XmlSeeAlso({ObjectFactory.class})
public interface OPEPackageWsTool {         
 
    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "onSaveOpePackage", targetNamespace = "http://ope.jdo/", className = "jdo.ope.client.OnSaveOpePackage")
    @WebMethod   
    @ResponseWrapper(localName = "onSaveOpePackageResponse", targetNamespace = "http://ope.jdo/", className = "jdo.ope.client.OnSaveOpePackageResponse")
    public java.lang.String onSaveOpePackage(                 
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,        
        @WebParam(name = "arg1", targetNamespace = "") 
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6
    );
}
