
package jdo.bil.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import jdo.bil.client.BILSPCINVWsTool;

import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

import com.dongyang.config.TConfig;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-05-05T10:29:57.300+08:00   
 * Generated source version: 2.5.2  
 * 
 */
public final class OPEPackageWsTool_OPEPackageWsToolImplPort_Client {
 
	public static final QName SERVICE_NAME = new QName("http://ope.jdo/", "OPEPackageWsToolImplService");

	public OPEPackageWsTool_OPEPackageWsToolImplPort_Client() {
    }
	                             
    private static  TConfig getProp() { 
        TConfig config = TConfig.getConfig("WEB-INF\\config\\system\\TConfig.x");
        return config;
	} 
 
    public  static String getWebServicesIp(){
		 TConfig config = getProp() ;  
		 String url = config.getString("", "WEB_SERVICES_IP");
		 return url;
	 }
	
    public  String onSaveOpePackage(String opCode,String supTypeCode, String opDateS, String opDateE,String state,String optUser ,String optTerm){    	 
  	     String ip = getWebServicesIp();         
  	     System.out.println("ip:"+ip);
   	   String url = "http://"+ip+"/services/opeService" ;   
   	   JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();   
       factory.setAddress(url); 
       factory.setServiceClass(OPEPackageWsTool.class);   
       //factory.getInInterceptors().add(new LoggingInInterceptor()); 
       OPEPackageWsTool service = (OPEPackageWsTool) factory.create();     
       System.out.println("client-opCode:"+opCode);
       System.out.println("client-supTypeCode:"+supTypeCode);
       System.out.println("client-opDateS:"+opDateS); 
       System.out.println("client-opDateE:"+opDateE);  
       System.out.println("client-state:"+state);
       System.out.println("client-optUser:"+optUser);
       System.out.println("client-optTerm:"+optTerm);
       String result = service.onSaveOpePackage(opCode, supTypeCode,opDateS,opDateE,state,optUser,optTerm);
       System.out.println("onSaveOpePackage---result:"+result);  
       return result;
  }
    
	  public static void main(String args[]) throws java.lang.Exception {
		  
	   }
  
//    public static void main(String args[]) throws java.lang.Exception {
//        URL wsdlURL = OPEPackageWsToolImplService.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {  
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//      
//        OPEPackageWsToolImplService ss = new OPEPackageWsToolImplService(wsdlURL, SERVICE_NAME);
//        OPEPackageWsTool port = ss.getOPEPackageWsToolImplPort();  
//        
//        {
//        System.out.println("Invoking onSaveOpePackage...");
//        java.lang.String _onSaveOpePackage_arg0 = "";
//        java.lang.String _onSaveOpePackage_arg1 = "";  
//        java.lang.String _onSaveOpePackage_arg2 = "";
//        java.lang.String _onSaveOpePackage_arg3 = "";
//        java.lang.String _onSaveOpePackage_arg4 = "";
//        java.lang.String _onSaveOpePackage_arg5 = "";
//        java.lang.String _onSaveOpePackage_arg6 = "";
//        java.lang.String _onSaveOpePackage__return = port.onSaveOpePackage(_onSaveOpePackage_arg0, _onSaveOpePackage_arg1, _onSaveOpePackage_arg2, _onSaveOpePackage_arg3, _onSaveOpePackage_arg4, _onSaveOpePackage_arg5, _onSaveOpePackage_arg6);
//        System.out.println("onSaveOpePackage.result=" + _onSaveOpePackage__return);
//
//
//        }
//
//        System.exit(0);
//    }

}
