package jdo.bil.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-05-05T10:29:57.368+08:00
 * Generated source version: 2.5.2
 * 
 */  
@WebServiceClient(name = "OPEPackageWsToolImplService", 
                  wsdlLocation = "http://127.0.0.1:8080/webwz/services/opeService?wsdl",
                  targetNamespace = "http://ope.jdo/") 
public class OPEPackageWsToolImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ope.jdo/", "OPEPackageWsToolImplService");
    public final static QName OPEPackageWsToolImplPort = new QName("http://ope.jdo/", "OPEPackageWsToolImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/webwz/services/opeService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OPEPackageWsToolImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/webwz/services/opeService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OPEPackageWsToolImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OPEPackageWsToolImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OPEPackageWsToolImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
       
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OPEPackageWsToolImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE); 
    }            

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OPEPackageWsToolImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OPEPackageWsToolImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns OPEPackageWsTool
     */
    @WebEndpoint(name = "OPEPackageWsToolImplPort")
    public OPEPackageWsTool getOPEPackageWsToolImplPort() {
        return super.getPort(OPEPackageWsToolImplPort, OPEPackageWsTool.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OPEPackageWsTool
     */
    @WebEndpoint(name = "OPEPackageWsToolImplPort")
    public OPEPackageWsTool getOPEPackageWsToolImplPort(WebServiceFeature... features) {
        //return super.getPort(OPEPackageWsToolImplPort, OPEPackageWsTool.class, features);
    	return null;
    }

}
