package jdo.reg.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ServiceForTXYYHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiceForTXYYHttpPost {

	/**
	 * 
	 * @param startDate
	 * @param endDate
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetQyiPayData")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getQyiPayData(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "start_date") String startDate,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "end_date") String endDate);

}
