package jdo.reg.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ServiceForTXYY service = new ServiceForTXYY();
 * ServiceForTXYYSoap portType = service.getServiceForTXYYSoap();
 * portType.getQyiPayData(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ServiceForTXYY", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://182.92.238.26:7777/WebService/ServiceForTXYY.asmx?WSDL")
public class ServiceForTXYY extends Service {

	private final static URL SERVICEFORTXYY_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(jdo.reg.client.ServiceForTXYY.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = jdo.reg.client.ServiceForTXYY.class.getResource(".");
			url = new URL(baseUrl,
					"http://182.92.238.26:7777/WebService/ServiceForTXYY.asmx?WSDL");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://182.92.238.26:7777/WebService/ServiceForTXYY.asmx?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SERVICEFORTXYY_WSDL_LOCATION = url;
	}

	public ServiceForTXYY(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ServiceForTXYY() {
		super(SERVICEFORTXYY_WSDL_LOCATION, new QName("http://tempuri.org/",
				"ServiceForTXYY"));
	}

	/**
	 * 
	 * @return returns ServiceForTXYYSoap
	 */
	@WebEndpoint(name = "ServiceForTXYYSoap")
	public ServiceForTXYYSoap getServiceForTXYYSoap() {
		return super.getPort(new QName("http://tempuri.org/",
				"ServiceForTXYYSoap"), ServiceForTXYYSoap.class);
	}

	/**
	 * 
	 * @return returns ServiceForTXYYSoap
	 */
	@WebEndpoint(name = "ServiceForTXYYSoap12")
	public ServiceForTXYYSoap getServiceForTXYYSoap12() {
		return super.getPort(new QName("http://tempuri.org/",
				"ServiceForTXYYSoap12"), ServiceForTXYYSoap.class);
	}

	/**
	 * 
	 * @return returns ServiceForTXYYHttpGet
	 */
	@WebEndpoint(name = "ServiceForTXYYHttpGet")
	public ServiceForTXYYHttpGet getServiceForTXYYHttpGet() {
		return super.getPort(new QName("http://tempuri.org/",
				"ServiceForTXYYHttpGet"), ServiceForTXYYHttpGet.class);
	}

	/**
	 * 
	 * @return returns ServiceForTXYYHttpPost
	 */
	@WebEndpoint(name = "ServiceForTXYYHttpPost")
	public ServiceForTXYYHttpPost getServiceForTXYYHttpPost() {
		return super.getPort(new QName("http://tempuri.org/",
				"ServiceForTXYYHttpPost"), ServiceForTXYYHttpPost.class);
	}

}
