package jdo.reg.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ServiceForTXYYSoap", targetNamespace = "http://tempuri.org/")
public interface ServiceForTXYYSoap {

	/**
	 * 
	 * @param startDate
	 * @param endDate
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetQyiPayData", action = "http://tempuri.org/GetQyiPayData")
	@WebResult(name = "GetQyiPayDataResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetQyiPayData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQyiPayData")
	@ResponseWrapper(localName = "GetQyiPayDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQyiPayDataResponse")
	public String getQyiPayData(
			@WebParam(name = "start_date", targetNamespace = "http://tempuri.org/") String startDate,
			@WebParam(name = "end_date", targetNamespace = "http://tempuri.org/") String endDate);

}
