package jdo.device.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.11
 * 2017-02-03T10:23:13.692+08:00
 * Generated source version: 2.5.11
 * 
 */
@WebServiceClient(name = "CamsCommService", 
                  wsdlLocation = "http://172.20.10.21/CommServicePub/CamsCommService.asmx?WSDL",
                  targetNamespace = "http://www.njnu.edu.cn/") 
public class CamsCommService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.njnu.edu.cn/", "CamsCommService");
    public final static QName CamsCommServiceSoap = new QName("http://www.njnu.edu.cn/", "CamsCommServiceSoap");
    public final static QName CamsCommServiceSoap12 = new QName("http://www.njnu.edu.cn/", "CamsCommServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://172.20.10.21/CommServicePub/CamsCommService.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CamsCommService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.20.10.21/CommServicePub/CamsCommService.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public CamsCommService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CamsCommService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CamsCommService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
   

    /**
     *
     * @return
     *     returns CamsCommServiceSoap
     */
    @WebEndpoint(name = "CamsCommServiceSoap")
    public CamsCommServiceSoap getCamsCommServiceSoap() {
        return super.getPort(CamsCommServiceSoap, CamsCommServiceSoap.class);
    }

    
    /**
     *
     * @return
     *     returns CamsCommServiceSoap
     */
    @WebEndpoint(name = "CamsCommServiceSoap12")
    public CamsCommServiceSoap getCamsCommServiceSoap12() {
        return super.getPort(CamsCommServiceSoap12, CamsCommServiceSoap.class);
    }

    
}
