
package jdo.device.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.11
 * 2017-02-03T10:23:13.667+08:00
 * Generated source version: 2.5.11
 * 
 */
public final class CamsCommServiceSoap_CamsCommServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.njnu.edu.cn/", "CamsCommService");

    private CamsCommServiceSoap_CamsCommServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CamsCommService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CamsCommService ss = new CamsCommService(wsdlURL, SERVICE_NAME);
        CamsCommServiceSoap port = ss.getCamsCommServiceSoap12();  
        
        {
        System.out.println("Invoking sendMsg...");
        java.lang.String _sendMsg_host = "";
        int _sendMsg_port = 0;
        short _sendMsg_msgType = Short.parseShort("0");
        java.lang.String _sendMsg_msg = "";
        int _sendMsg__return = port.sendMsg(_sendMsg_host, _sendMsg_port, _sendMsg_msgType, _sendMsg_msg);
        System.out.println("sendMsg.result=" + _sendMsg__return);


        }
        {
        System.out.println("Invoking helloWorld...");
        java.lang.String _helloWorld__return = port.helloWorld();
        System.out.println("helloWorld.result=" + _helloWorld__return);


        }

        System.exit(0);
    }

}
