
package jdo.device.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.StringReader;

import javax.xml.bind.JAXB;

import jdo.device.CallNoXmlCurrentCamsInfo;

import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

import com.dongyang.config.TConfig;
import com.dongyang.data.TParm;

/**
 * This class was generated by Apache CXF 2.5.11
 * 2017-02-03T10:23:13.588+08:00
 * Generated source version: 2.5.11
 * 
 */
public final class CamsCommServiceSoap_Client {

public static CamsCommServiceSoap_Client instance;
    
    public static CamsCommServiceSoap_Client getInstance() {
        if (instance == null) {
            instance = new CamsCommServiceSoap_Client();
        }
        return instance;
    }
    
    private static JaxWsProxyFactoryBean jaxFactory;
    
    private static JaxWsProxyFactoryBean getJaxFactory(){
        if(jaxFactory == null){
            jaxFactory = new JaxWsProxyFactoryBean();
        }
        return jaxFactory;
    }
    
    public int sendMsg(short msgType,String msg){
        String ip = getWebServicesIp();
        JaxWsProxyFactoryBean factory = getJaxFactory();
        factory.setAddress("http://" + ip + "/CommServicePub/CamsCommService.asmx?WSDL");
        factory.setServiceClass(CamsCommServiceSoap.class);
        String host=getHost();
        int port=getPort();
        CamsCommServiceSoap service = (CamsCommServiceSoap) factory.create();
        int result = service.sendMsg(host, port, msgType, msg);
        return result;
        
    }
    
    /**
     * 获取当前叫号病患信息
     * 
     * @param devName 客户端IP
     * @return
     */
    public TParm getCurrentCallCamsInfo(String devName) {
        TParm result = new TParm();
        try {
            String ip = getWebServicesIp();
            JaxWsProxyFactoryBean factory = getJaxFactory();
            factory.setAddress("http://" + ip
                    + "/CommServicePub/CamsCommService.asmx?WSDL");
            factory.setServiceClass(CamsCommServiceSoap.class);
            CamsCommServiceSoap service = (CamsCommServiceSoap) factory
                    .create();
            String xmlResult = service.getCurrentCallCamsInfo(devName);
            StringReader read = new StringReader(xmlResult);
            CallNoXmlCurrentCamsInfo currentCamsInfo = JAXB.unmarshal(read,
                    CallNoXmlCurrentCamsInfo.class);

            result.setData("MR_NO", currentCamsInfo.getPatientID());
            result.setData("PAT_NAME", currentCamsInfo.getName());
            result.setData("QUE_NO", currentCamsInfo.getSerialNum());
        } catch (Exception e) {
            result.setErr(-1, "获取当前叫号病患信息异常");
            System.out.println("获取当前叫号病患信息异常:" + e.getMessage());
        }
        return result;
    }
    
    public TConfig getProp() {
        TConfig config = TConfig
                .getConfig("WEB-INF\\config\\system\\TConfig.x");
        return config;
    }

    public String getWebServicesIp() {
        TConfig config = getProp();
        String url = config.getString("", "CallNo_SERVICES_IP");
        return url;
    }

    public String getHost() {
        TConfig config = getProp();
        String host = config.getString("", "CallNo_SERVICES_Host");
        return host;
    }

    public int getPort() {
        TConfig config = getProp();
        int port = config.getInt("", "CallNo_SERVICES_Port");
        return port;
    }

}
