package action.emr.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.7
 * 2016-02-02T12:02:34.171+08:00
 * Generated source version: 3.0.7
 * 
 */
@WebService(targetNamespace = "http://172.20.10.152/signpdf/", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    @WebResult(name = "signPDFResult", targetNamespace = "http://172.20.10.152/signpdf/")
    @RequestWrapper(localName = "signPDF", targetNamespace = "http://172.20.10.152/signpdf/", className = "action.emr.client.SignPDF")
    @WebMethod(action = "http://172.20.10.152/signpdf/signPDF")
    @ResponseWrapper(localName = "signPDFResponse", targetNamespace = "http://172.20.10.152/signpdf/", className = "action.emr.client.SignPDFResponse")
    public java.lang.String signPDF(
        @WebParam(name = "fs", targetNamespace = "http://172.20.10.152/signpdf/")
        byte[] fs,
        @WebParam(name = "x", targetNamespace = "http://172.20.10.152/signpdf/")
        int x,
        @WebParam(name = "y", targetNamespace = "http://172.20.10.152/signpdf/")
        int y,
        @WebParam(name = "w", targetNamespace = "http://172.20.10.152/signpdf/")
        int w,
        @WebParam(name = "h", targetNamespace = "http://172.20.10.152/signpdf/")
        int h,
        @WebParam(name = "p", targetNamespace = "http://172.20.10.152/signpdf/")
        int p
    );
}
