package jdo.adm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.7
 * 2018-01-17T16:39:36.365+08:00
 * Generated source version: 3.0.7
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "QYIToHISWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface QYIToHISWebServiceSoap {

    @WebResult(name = "ValidateBackMoneyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateBackMoney", targetNamespace = "http://tempuri.org/", className = "jdo.adm.client.ValidateBackMoney")
    @WebMethod(operationName = "ValidateBackMoney", action = "http://tempuri.org/ValidateBackMoney")
    @ResponseWrapper(localName = "ValidateBackMoneyResponse", targetNamespace = "http://tempuri.org/", className = "jdo.adm.client.ValidateBackMoneyResponse")
    public java.lang.String validateBackMoney(
        @WebParam(name = "inXML", targetNamespace = "http://tempuri.org/")
        java.lang.String inXML
    );

    @WebResult(name = "BackMoneyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BackMoney", targetNamespace = "http://tempuri.org/", className = "jdo.adm.client.BackMoney")
    @WebMethod(operationName = "BackMoney", action = "http://tempuri.org/BackMoney")
    @ResponseWrapper(localName = "BackMoneyResponse", targetNamespace = "http://tempuri.org/", className = "jdo.adm.client.BackMoneyResponse")
    public java.lang.String backMoney(
        @WebParam(name = "inXML", targetNamespace = "http://tempuri.org/")
        java.lang.String inXML
    );

    @WebResult(name = "UpdateHospitalInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateHospitalInfo", targetNamespace = "http://tempuri.org/", className = "jdo.adm.client.UpdateHospitalInfo")
    @WebMethod(operationName = "UpdateHospitalInfo", action = "http://tempuri.org/UpdateHospitalInfo")
    @ResponseWrapper(localName = "UpdateHospitalInfoResponse", targetNamespace = "http://tempuri.org/", className = "jdo.adm.client.UpdateHospitalInfoResponse")
    public java.lang.String updateHospitalInfo(
        @WebParam(name = "inXML", targetNamespace = "http://tempuri.org/")
        java.lang.String inXML
    );
}
