//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.13 at 10:02:29 ÉÏÎç CST 
//


package jdo.sum.bean;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jdo.sum.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PulseUnit_QNAME = new QName("", "pulseUnit");
    private final static QName _InputNum_QNAME = new QName("", "inputNum");
    private final static QName _HeartRate_QNAME = new QName("", "heartRate");
    private final static QName _Tel_QNAME = new QName("", "tel");
    private final static QName _ReceiveApp_QNAME = new QName("", "receiveApp");
    private final static QName _NormalStool_QNAME = new QName("", "normalStool");
    private final static QName _Diastolic_QNAME = new QName("", "diastolic");
    private final static QName _Temperature_QNAME = new QName("", "temperature");
    private final static QName _VsDrCode_QNAME = new QName("", "vsDrCode");
    private final static QName _SendApp_QNAME = new QName("", "sendApp");
    private final static QName _Enema_QNAME = new QName("", "enema");
    private final static QName _BirthDate_QNAME = new QName("", "birthDate");
    private final static QName _Dept_QNAME = new QName("", "dept");
    private final static QName _Breath_QNAME = new QName("", "breath");
    private final static QName _CreateUserId_QNAME = new QName("", "createUserId");
    private final static QName _IdNo_QNAME = new QName("", "idNo");
    private final static QName _BreathUnit_QNAME = new QName("", "breathUnit");
    private final static QName _OrderDate_QNAME = new QName("", "orderDate");
    private final static QName _Bed_QNAME = new QName("", "bed");
    private final static QName _AdmType_QNAME = new QName("", "admType");
    private final static QName _HeartRateUnit_QNAME = new QName("", "heartRateUnit");
    private final static QName _SendDate_QNAME = new QName("", "sendDate");
    private final static QName _SystolicUnit_QNAME = new QName("", "systolicUnit");
    private final static QName _Company_QNAME = new QName("", "company");
    private final static QName _CtzDesc_QNAME = new QName("", "ctzDesc");
    private final static QName _OutputNum_QNAME = new QName("", "outputNum");
    private final static QName _DiastolicUnit_QNAME = new QName("", "diastolicUnit");
    private final static QName _Room_QNAME = new QName("", "room");
    private final static QName _Sex_QNAME = new QName("", "sex");
    private final static QName _Weight_QNAME = new QName("", "weight");
    private final static QName _InDate_QNAME = new QName("", "inDate");
    private final static QName _OutDate_QNAME = new QName("", "outDate");
    private final static QName _Pulse_QNAME = new QName("", "pulse");
    private final static QName _TemperatureType_QNAME = new QName("", "temperatureType");
    private final static QName _Version_QNAME = new QName("", "version");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _CreateUserName_QNAME = new QName("", "createUserName");
    private final static QName _TemperatureUnit_QNAME = new QName("", "temperatureUnit");
    private final static QName _PatName_QNAME = new QName("", "patName");
    private final static QName _ValueType_QNAME = new QName("", "valueType");
    private final static QName _CaseNo_QNAME = new QName("", "caseNo");
    private final static QName _MrNo_QNAME = new QName("", "mrNo");
    private final static QName _RelationTel_QNAME = new QName("", "relationTel");
    private final static QName _Drainage_QNAME = new QName("", "drainage");
    private final static QName _Systolic_QNAME = new QName("", "systolic");
    private final static QName _Stool_QNAME = new QName("", "stool");
    private final static QName _OrderTime_QNAME = new QName("", "orderTime");
    private final static QName _MessageType_QNAME = new QName("", "messageType");
    private final static QName _Marriage_QNAME = new QName("", "marriage");
    private final static QName _WorkAddress_QNAME = new QName("", "workAddress");
    private final static QName _Address_QNAME = new QName("", "address");
    private final static QName _High_QNAME = new QName("", "high");
    private final static QName _AdmDr_QNAME = new QName("", "admDr");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jdo.sum.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObxList }
     * 
     */
    public ObxList createObxList() {
        return new ObxList();
    }

    /**
     * Create an instance of {@link Obx }
     * 
     */
    public Obx createObx() {
        return new Obx();
    }

    /**
     * Create an instance of {@link Pv1 }
     * 
     */
    public Pv1 createPv1() {
        return new Pv1();
    }

    /**
     * Create an instance of {@link ObxOther }
     * 
     */
    public ObxOther createObxOther() {
        return new ObxOther();
    }

    /**
     * Create an instance of {@link Msh }
     * 
     */
    public Msh createMsh() {
        return new Msh();
    }

    /**
     * Create an instance of {@link Pid }
     * 
     */
    public Pid createPid() {
        return new Pid();
    }

    /**
     * Create an instance of {@link Hl7 }
     * 
     */
    public Hl7 createHl7() {
        return new Hl7();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pulseUnit")
    public JAXBElement<String> createPulseUnit(String value) {
        return new JAXBElement<String>(_PulseUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "inputNum")
    public JAXBElement<BigDecimal> createInputNum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_InputNum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "heartRate")
    public JAXBElement<BigInteger> createHeartRate(BigInteger value) {
        return new JAXBElement<BigInteger>(_HeartRate_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tel")
    public JAXBElement<String> createTel(String value) {
        return new JAXBElement<String>(_Tel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "receiveApp")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReceiveApp(String value) {
        return new JAXBElement<String>(_ReceiveApp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "normalStool")
    public JAXBElement<BigInteger> createNormalStool(BigInteger value) {
        return new JAXBElement<BigInteger>(_NormalStool_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "diastolic")
    public JAXBElement<BigInteger> createDiastolic(BigInteger value) {
        return new JAXBElement<BigInteger>(_Diastolic_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "temperature")
    public JAXBElement<BigDecimal> createTemperature(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Temperature_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vsDrCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVsDrCode(String value) {
        return new JAXBElement<String>(_VsDrCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sendApp")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSendApp(String value) {
        return new JAXBElement<String>(_SendApp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "enema")
    public JAXBElement<BigInteger> createEnema(BigInteger value) {
        return new JAXBElement<BigInteger>(_Enema_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "birthDate")
    public JAXBElement<String> createBirthDate(String value) {
        return new JAXBElement<String>(_BirthDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dept")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDept(String value) {
        return new JAXBElement<String>(_Dept_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "breath")
    public JAXBElement<BigInteger> createBreath(BigInteger value) {
        return new JAXBElement<BigInteger>(_Breath_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "createUserId")
    public JAXBElement<String> createCreateUserId(String value) {
        return new JAXBElement<String>(_CreateUserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "idNo")
    public JAXBElement<String> createIdNo(String value) {
        return new JAXBElement<String>(_IdNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "breathUnit")
    public JAXBElement<String> createBreathUnit(String value) {
        return new JAXBElement<String>(_BreathUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orderDate")
    public JAXBElement<String> createOrderDate(String value) {
        return new JAXBElement<String>(_OrderDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bed")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBed(String value) {
        return new JAXBElement<String>(_Bed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "admType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAdmType(String value) {
        return new JAXBElement<String>(_AdmType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "heartRateUnit")
    public JAXBElement<String> createHeartRateUnit(String value) {
        return new JAXBElement<String>(_HeartRateUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sendDate")
    public JAXBElement<String> createSendDate(String value) {
        return new JAXBElement<String>(_SendDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "systolicUnit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSystolicUnit(String value) {
        return new JAXBElement<String>(_SystolicUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "company")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCompany(String value) {
        return new JAXBElement<String>(_Company_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ctzDesc")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCtzDesc(String value) {
        return new JAXBElement<String>(_CtzDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "outputNum")
    public JAXBElement<BigDecimal> createOutputNum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_OutputNum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "diastolicUnit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDiastolicUnit(String value) {
        return new JAXBElement<String>(_DiastolicUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "room")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRoom(String value) {
        return new JAXBElement<String>(_Room_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sex")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSex(String value) {
        return new JAXBElement<String>(_Sex_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "weight")
    public JAXBElement<BigDecimal> createWeight(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Weight_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "inDate")
    public JAXBElement<String> createInDate(String value) {
        return new JAXBElement<String>(_InDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "outDate")
    public JAXBElement<String> createOutDate(String value) {
        return new JAXBElement<String>(_OutDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pulse")
    public JAXBElement<BigInteger> createPulse(BigInteger value) {
        return new JAXBElement<BigInteger>(_Pulse_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "temperatureType")
    public JAXBElement<String> createTemperatureType(String value) {
        return new JAXBElement<String>(_TemperatureType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    public JAXBElement<BigInteger> createId(BigInteger value) {
        return new JAXBElement<BigInteger>(_Id_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "createUserName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCreateUserName(String value) {
        return new JAXBElement<String>(_CreateUserName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "temperatureUnit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTemperatureUnit(String value) {
        return new JAXBElement<String>(_TemperatureUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "patName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPatName(String value) {
        return new JAXBElement<String>(_PatName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "valueType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createValueType(String value) {
        return new JAXBElement<String>(_ValueType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "caseNo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCaseNo(String value) {
        return new JAXBElement<String>(_CaseNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mrNo")
    public JAXBElement<String> createMrNo(String value) {
        return new JAXBElement<String>(_MrNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "relationTel")
    public JAXBElement<String> createRelationTel(String value) {
        return new JAXBElement<String>(_RelationTel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "drainage")
    public JAXBElement<BigDecimal> createDrainage(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Drainage_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "systolic")
    public JAXBElement<BigInteger> createSystolic(BigInteger value) {
        return new JAXBElement<BigInteger>(_Systolic_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stool")
    public JAXBElement<BigInteger> createStool(BigInteger value) {
        return new JAXBElement<BigInteger>(_Stool_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orderTime")
    public JAXBElement<String> createOrderTime(String value) {
        return new JAXBElement<String>(_OrderTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "messageType")
    public JAXBElement<String> createMessageType(String value) {
        return new JAXBElement<String>(_MessageType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "marriage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMarriage(String value) {
        return new JAXBElement<String>(_Marriage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "workAddress")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createWorkAddress(String value) {
        return new JAXBElement<String>(_WorkAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAddress(String value) {
        return new JAXBElement<String>(_Address_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "high")
    public JAXBElement<BigDecimal> createHigh(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_High_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "admDr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAdmDr(String value) {
        return new JAXBElement<String>(_AdmDr_QNAME, String.class, null, value);
    }

}
