//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.13 at 10:02:29 ÉÏÎç CST 
//


package jdo.sum.bean;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}id"/>
 *         &lt;element ref="{}valueType"/>
 *         &lt;element ref="{}orderDate"/>
 *         &lt;element ref="{}orderTime"/>
 *         &lt;element ref="{}temperatureType"/>
 *         &lt;element ref="{}temperature"/>
 *         &lt;element ref="{}pulse"/>
 *         &lt;element ref="{}breath"/>
 *         &lt;element ref="{}systolic"/>
 *         &lt;element ref="{}diastolic"/>
 *         &lt;element ref="{}heartRate"/>
 *         &lt;element ref="{}temperatureUnit"/>
 *         &lt;element ref="{}pulseUnit"/>
 *         &lt;element ref="{}breathUnit"/>
 *         &lt;element ref="{}systolicUnit"/>
 *         &lt;element ref="{}diastolicUnit"/>
 *         &lt;element ref="{}heartRateUnit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "valueType",
    "orderDate",
    "orderTime",
    "temperatureType",
    "temperature",
    "pulse",
    "breath",
    "systolic",
    "diastolic",
    "heartRate",
    "temperatureUnit",
    "pulseUnit",
    "breathUnit",
    "systolicUnit",
    "diastolicUnit",
    "heartRateUnit"
})
@XmlRootElement(name = "obx")
public class Obx {

    @XmlElement(required = true)
    protected BigInteger id;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String valueType;
    @XmlElement(required = true)
    protected String orderDate;
    @XmlElement(required = true)
    protected String orderTime;
    @XmlElement(required = true)
    protected String temperatureType;
    @XmlElement(required = true)
    protected BigDecimal temperature;
    @XmlElement(required = true)
    protected BigInteger pulse;
    @XmlElement(required = true)
    protected BigInteger breath;
    @XmlElement(required = true)
    protected BigInteger systolic;
    @XmlElement(required = true)
    protected BigInteger diastolic;
    @XmlElement(required = true)
    protected BigInteger heartRate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String temperatureUnit;
    @XmlElement(required = true)
    protected String pulseUnit;
    @XmlElement(required = true)
    protected String breathUnit;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String systolicUnit;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String diastolicUnit;
    @XmlElement(required = true)
    protected String heartRateUnit;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the valueType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueType() {
        return valueType;
    }

    /**
     * Sets the value of the valueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueType(String value) {
        this.valueType = value;
    }

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDate(String value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the orderTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * Sets the value of the orderTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderTime(String value) {
        this.orderTime = value;
    }

    /**
     * Gets the value of the temperatureType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemperatureType() {
        return temperatureType;
    }

    /**
     * Sets the value of the temperatureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemperatureType(String value) {
        this.temperatureType = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTemperature(BigDecimal value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the pulse property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPulse() {
        return pulse;
    }

    /**
     * Sets the value of the pulse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPulse(BigInteger value) {
        this.pulse = value;
    }

    /**
     * Gets the value of the breath property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBreath() {
        return breath;
    }

    /**
     * Sets the value of the breath property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBreath(BigInteger value) {
        this.breath = value;
    }

    /**
     * Gets the value of the systolic property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSystolic() {
        return systolic;
    }

    /**
     * Sets the value of the systolic property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSystolic(BigInteger value) {
        this.systolic = value;
    }

    /**
     * Gets the value of the diastolic property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDiastolic() {
        return diastolic;
    }

    /**
     * Sets the value of the diastolic property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDiastolic(BigInteger value) {
        this.diastolic = value;
    }

    /**
     * Gets the value of the heartRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeartRate() {
        return heartRate;
    }

    /**
     * Sets the value of the heartRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeartRate(BigInteger value) {
        this.heartRate = value;
    }

    /**
     * Gets the value of the temperatureUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemperatureUnit() {
        return temperatureUnit;
    }

    /**
     * Sets the value of the temperatureUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemperatureUnit(String value) {
        this.temperatureUnit = value;
    }

    /**
     * Gets the value of the pulseUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPulseUnit() {
        return pulseUnit;
    }

    /**
     * Sets the value of the pulseUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPulseUnit(String value) {
        this.pulseUnit = value;
    }

    /**
     * Gets the value of the breathUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreathUnit() {
        return breathUnit;
    }

    /**
     * Sets the value of the breathUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreathUnit(String value) {
        this.breathUnit = value;
    }

    /**
     * Gets the value of the systolicUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystolicUnit() {
        return systolicUnit;
    }

    /**
     * Sets the value of the systolicUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystolicUnit(String value) {
        this.systolicUnit = value;
    }

    /**
     * Gets the value of the diastolicUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiastolicUnit() {
        return diastolicUnit;
    }

    /**
     * Sets the value of the diastolicUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiastolicUnit(String value) {
        this.diastolicUnit = value;
    }

    /**
     * Gets the value of the heartRateUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeartRateUnit() {
        return heartRateUnit;
    }

    /**
     * Sets the value of the heartRateUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeartRateUnit(String value) {
        this.heartRateUnit = value;
    }

}
