//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.13 at 10:02:29 ÉÏÎç CST 
//


package jdo.sum.bean;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}orderDate"/>
 *         &lt;element ref="{}orderTime"/>
 *         &lt;element ref="{}inputNum"/>
 *         &lt;element ref="{}outputNum"/>
 *         &lt;element ref="{}stool"/>
 *         &lt;element ref="{}normalStool"/>
 *         &lt;element ref="{}enema"/>
 *         &lt;element ref="{}drainage"/>
 *         &lt;element ref="{}weight"/>
 *         &lt;element ref="{}high"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderDate",
    "orderTime",
    "inputNum",
    "outputNum",
    "stool",
    "normalStool",
    "enema",
    "drainage",
    "weight",
    "high"
})
@XmlRootElement(name = "obxOther")
public class ObxOther {

    @XmlElement(required = true)
    protected String orderDate;
    @XmlElement(required = true)
    protected String orderTime;
    @XmlElement(required = true)
    protected BigDecimal inputNum;
    @XmlElement(required = true)
    protected BigDecimal outputNum;
    @XmlElement(required = true)
    protected BigInteger stool;
    @XmlElement(required = true)
    protected BigInteger normalStool;
    @XmlElement(required = true)
    protected BigInteger enema;
    @XmlElement(required = true)
    protected BigDecimal drainage;
    @XmlElement(required = true)
    protected BigDecimal weight;
    @XmlElement(required = true)
    protected BigDecimal high;

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDate(String value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the orderTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * Sets the value of the orderTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderTime(String value) {
        this.orderTime = value;
    }

    /**
     * Gets the value of the inputNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInputNum() {
        return inputNum;
    }

    /**
     * Sets the value of the inputNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInputNum(BigDecimal value) {
        this.inputNum = value;
    }

    /**
     * Gets the value of the outputNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOutputNum() {
        return outputNum;
    }

    /**
     * Sets the value of the outputNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOutputNum(BigDecimal value) {
        this.outputNum = value;
    }

    /**
     * Gets the value of the stool property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStool() {
        return stool;
    }

    /**
     * Sets the value of the stool property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStool(BigInteger value) {
        this.stool = value;
    }

    /**
     * Gets the value of the normalStool property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNormalStool() {
        return normalStool;
    }

    /**
     * Sets the value of the normalStool property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNormalStool(BigInteger value) {
        this.normalStool = value;
    }

    /**
     * Gets the value of the enema property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEnema() {
        return enema;
    }

    /**
     * Sets the value of the enema property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEnema(BigInteger value) {
        this.enema = value;
    }

    /**
     * Gets the value of the drainage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDrainage() {
        return drainage;
    }

    /**
     * Sets the value of the drainage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDrainage(BigDecimal value) {
        this.drainage = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeight(BigDecimal value) {
        this.weight = value;
    }

    /**
     * Gets the value of the high property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHigh() {
        return high;
    }

    /**
     * Sets the value of the high property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHigh(BigDecimal value) {
        this.high = value;
    }

}
