package jdo.cdss;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-04-15T17:23:52.103+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "CDSSImplService", 
                  wsdlLocation = "http://172.20.10.82:8080/drools/services/cdss?wsdl",
                  targetNamespace = "http://service.zhangp.com/") 
public class CDSSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.zhangp.com/", "CDSSImplService");
    public final static QName CDSSImplPort = new QName("http://service.zhangp.com/", "CDSSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.20.10.82:8080/drools/services/cdss?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CDSSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.20.10.82:8080/drools/services/cdss?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CDSSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CDSSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CDSSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CDSSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CDSSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CDSSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }    

    /**
     *
     * @return
     *     returns ICDSSService
     */
    @WebEndpoint(name = "CDSSImplPort")
    public ICDSSService getCDSSImplPort() {
        return super.getPort(CDSSImplPort, ICDSSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICDSSService
     */
    @WebEndpoint(name = "CDSSImplPort")
    public ICDSSService getCDSSImplPort(WebServiceFeature... features) {
        //return super.getPort(CDSSImplPort, ICDSSService.class, features);
    	return null;
    }

}
