package jdo.cdss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2015-08-14T13:38:24.458+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://service.zhangp.com/", name = "ICDSSService2")
@XmlSeeAlso({ObjectFactory.class})
public interface ICDSSService2 {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fireRule2", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule2")
    @WebMethod
    @ResponseWrapper(localName = "fireRule2Response", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule2Response")
    public jdo.cdss.HisPojo fireRule2(
        @WebParam(name = "arg0", targetNamespace = "")
        jdo.cdss.HisPojo arg0
    );
}
