package jdo.cdss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2015-08-14T13:17:09.019+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://service.zhangp.com/", name = "ICDSSService1")
@XmlSeeAlso({ObjectFactory.class})
public interface ICDSSService1 {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fireRule1", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule1")
    @WebMethod
    @ResponseWrapper(localName = "fireRule1Response", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule1Response")
    public jdo.cdss.HisPojo fireRule1(
        @WebParam(name = "arg0", targetNamespace = "")
        jdo.cdss.HisPojo arg0
    );
}
