package jdo.cdss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2015-08-31T10:42:03.881+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://service.zhangp.com/", name = "ICDSSService5")
@XmlSeeAlso({ObjectFactory.class})
public interface ICDSSService5 {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fireRule5", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule5")
    @WebMethod
    @ResponseWrapper(localName = "fireRule5Response", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule5Response")
    public jdo.cdss.HisPojo fireRule5(
        @WebParam(name = "arg0", targetNamespace = "")
        jdo.cdss.HisPojo arg0
    );
}
