
package jdo.cdss;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-04-29T23:35:56.506+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class ICDSSService_CDSSImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.zhangp.com/", "CDSSImplService");

    private ICDSSService_CDSSImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CDSSImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CDSSImplService ss = new CDSSImplService(wsdlURL, SERVICE_NAME);
        ICDSSService port = ss.getCDSSImplPort();  
        
        {
        System.out.println("Invoking fireRule3...");
        jdo.cdss.HisPojo _fireRule3_arg0 = null;
        jdo.cdss.HisPojo _fireRule3__return = port.fireRule3(_fireRule3_arg0);
        System.out.println("fireRule3.result=" + _fireRule3__return);


        }
        {
        System.out.println("Invoking fireRule1...");
        jdo.cdss.HisPojo _fireRule1_arg0 = null;
        jdo.cdss.HisPojo _fireRule1__return = port.fireRule1(_fireRule1_arg0);
        System.out.println("fireRule1.result=" + _fireRule1__return);


        }
        {
        System.out.println("Invoking fireRule2...");
        jdo.cdss.HisPojo _fireRule2_arg0 = null;
        jdo.cdss.HisPojo _fireRule2__return = port.fireRule2(_fireRule2_arg0);
        System.out.println("fireRule2.result=" + _fireRule2__return);


        }

        System.exit(0);
    }

}
