
package jdo.cdss;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2015-08-14T13:43:15.254+08:00
 * Generated source version: 2.7.8
 * 
 */
public final class ICDSSService4_CDSS4ImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.zhangp.com/", "CDSS4ImplService");

    private ICDSSService4_CDSS4ImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CDSS4ImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CDSS4ImplService ss = new CDSS4ImplService(wsdlURL, SERVICE_NAME);
        ICDSSService4 port = ss.getCDSS4ImplPort();  
        
        {
        System.out.println("Invoking fireRule4...");
        jdo.cdss.ClpPojo _fireRule4_arg0 = null;
        jdo.cdss.ClpPojo _fireRule4__return = port.fireRule4(_fireRule4_arg0);
        System.out.println("fireRule4.result=" + _fireRule4__return);


        }

        System.exit(0);
    }

}
