package jdo.cdss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2015-08-14T13:43:15.299+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://service.zhangp.com/", name = "ICDSSService4")
@XmlSeeAlso({ObjectFactory.class})
public interface ICDSSService4 {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fireRule4", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule4")
    @WebMethod
    @ResponseWrapper(localName = "fireRule4Response", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule4Response")
    public jdo.cdss.ClpPojo fireRule4(
        @WebParam(name = "arg0", targetNamespace = "")
        jdo.cdss.ClpPojo arg0
    );
}
