package jdo.cdss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-04-29T23:35:56.584+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://service.zhangp.com/", name = "ICDSSService")
@XmlSeeAlso({ObjectFactory.class})
public interface ICDSSService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fireRule3", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule3")
    @WebMethod
    @ResponseWrapper(localName = "fireRule3Response", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule3Response")
    public jdo.cdss.HisPojo fireRule3(
        @WebParam(name = "arg0", targetNamespace = "")
        jdo.cdss.HisPojo arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fireRule1", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule1")
    @WebMethod
    @ResponseWrapper(localName = "fireRule1Response", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule1Response")
    public jdo.cdss.HisPojo fireRule1(
        @WebParam(name = "arg0", targetNamespace = "")
        jdo.cdss.HisPojo arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fireRule2", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule2")
    @WebMethod
    @ResponseWrapper(localName = "fireRule2Response", targetNamespace = "http://service.zhangp.com/", className = "jdo.cdss.FireRule2Response")
    public jdo.cdss.HisPojo fireRule2(
        @WebParam(name = "arg0", targetNamespace = "")
        jdo.cdss.HisPojo arg0
    );
}
